---
# tasks file for ansible-pull
- name: install units for ansible-pull
  become: true
  ansible.builtin.template:
    dest: /etc/systemd/system
    src: "{{ item.name }}"
  loop:
    - name: ansible-pull.service
    - name: ansible-pull.timer
  loop_control:
    label: "{{ item.name }}"

- name: enable ansible-pull timer
  become: true
  ansible.builtin.service:
    name: ansible-pull.timer
    state: started
    enabled: yes
