---
# tasks file for ansible-pull
- name: install units for ansible-pull
  become: true
  ansible.builtin.template:
    dest: /etc/systemd/system
    src: "{{ item.item }}"
  loop:
    - ansible-pull.service
    - ansible-pull.timer
  

- name: enable ansible-pull timer
  become: true
  ansible.builtin.service:
    name: ansible-pull.timer
    state: started
    enabled: yes
